### ISSUE TITLE
Stylus いじる

### ISSUE THREAD

**Issue by 03hcl** [03-family/daily_lives#64]
Google Chrome の拡張機能
https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne/

**Comment by 03hcl** [comment]
自分のアカウントにインストールはした

**Comment by 03hcl** [comment]
会社PCでいろいろいじってみた
記事も書いた
また使うときはそれを参照したい

**Comment by 03hcl** [comment]
GitHub Issue に下記対応させる

コード:

```css
.timeline-comment .previewable-comment-form textarea {
  font-family: "ONLYWHITESPACE03HCL", "Fira Code", "IBM Plex Sans JP", monospace;
  /* letter-spacing: 0; */
}
```

(※フォントの "ONLYWHITESPACE03HCL" は #72 でインストールするもの)

適用先: `https://github.com/.*?/issues/.*?` (暫定)
